doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                url: '%env(DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4

            customer:
                # configure these for your database server
                url: '%env(DATABASE_CUSTOMER_URL)%'
                # driver: 'pdo_oci'
                driver: 'pdo_mysql'
                #server_version: ~
                server_version: '5.7'
                #charset: AL32UTF8
                charset: utf8mb4

            reports:
                # configure these for your database server
                url: '%env(DATABASE_REPORTS_URL)%'
                # driver: 'pdo_oci'
                driver: 'pdo_mysql'
                #server_version: ~
                server_version: '5.7'
                #charset: AL32UTF8
                charset: utf8mb4

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:

        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Main
            reports:
                connection: reports
                mappings:
                    Reports:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Reports'
                        prefix: 'App\Entity\Reports'
                        alias: Reports
