<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TEPSITE extends \App\Entity\TEPSITE implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TEPSITE' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TEPSITE' . "\0" . 'T_EP_SITE_EP_ID', '' . "\0" . 'App\\Entity\\TEPSITE' . "\0" . 'SITE', '' . "\0" . 'App\\Entity\\TEPSITE' . "\0" . 'DM_SITE_DESC', '' . "\0" . 'App\\Entity\\TEPSITE' . "\0" . 'XXAWG_STORE_NAME', '' . "\0" . 'App\\Entity\\TEPSITE' . "\0" . 'XXAWG_STORE_CITY', '' . "\0" . 'App\\Entity\\TEPSITE' . "\0" . 'XXAWG_STORE_ADD', '' . "\0" . 'App\\Entity\\TEPSITE' . "\0" . 'XXAWG_STORE_PHONE', '' . "\0" . 'App\\Entity\\TEPSITE' . "\0" . 'XXAWG_STORE_ZIP', '' . "\0" . 'App\\Entity\\TEPSITE' . "\0" . 'T_EP_PARENT_STORE_ID'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TEPSITE' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TEPSITE' . "\0" . 'T_EP_SITE_EP_ID', '' . "\0" . 'App\\Entity\\TEPSITE' . "\0" . 'SITE', '' . "\0" . 'App\\Entity\\TEPSITE' . "\0" . 'DM_SITE_DESC', '' . "\0" . 'App\\Entity\\TEPSITE' . "\0" . 'XXAWG_STORE_NAME', '' . "\0" . 'App\\Entity\\TEPSITE' . "\0" . 'XXAWG_STORE_CITY', '' . "\0" . 'App\\Entity\\TEPSITE' . "\0" . 'XXAWG_STORE_ADD', '' . "\0" . 'App\\Entity\\TEPSITE' . "\0" . 'XXAWG_STORE_PHONE', '' . "\0" . 'App\\Entity\\TEPSITE' . "\0" . 'XXAWG_STORE_ZIP', '' . "\0" . 'App\\Entity\\TEPSITE' . "\0" . 'T_EP_PARENT_STORE_ID'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TEPSITE $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTEPSITEEPID(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTEPSITEEPID', []);

        return parent::getTEPSITEEPID();
    }

    /**
     * {@inheritDoc}
     */
    public function setTEPSITEEPID(int $T_EP_SITE_EP_ID): \App\Entity\TEPSITE
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTEPSITEEPID', [$T_EP_SITE_EP_ID]);

        return parent::setTEPSITEEPID($T_EP_SITE_EP_ID);
    }

    /**
     * {@inheritDoc}
     */
    public function getSITE(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSITE', []);

        return parent::getSITE();
    }

    /**
     * {@inheritDoc}
     */
    public function setSITE(string $SITE): \App\Entity\TEPSITE
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSITE', [$SITE]);

        return parent::setSITE($SITE);
    }

    /**
     * {@inheritDoc}
     */
    public function getDMSITEDESC(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDMSITEDESC', []);

        return parent::getDMSITEDESC();
    }

    /**
     * {@inheritDoc}
     */
    public function setDMSITEDESC(string $DM_SITE_DESC): \App\Entity\TEPSITE
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDMSITEDESC', [$DM_SITE_DESC]);

        return parent::setDMSITEDESC($DM_SITE_DESC);
    }

    /**
     * {@inheritDoc}
     */
    public function getXXAWGSTORENAME(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getXXAWGSTORENAME', []);

        return parent::getXXAWGSTORENAME();
    }

    /**
     * {@inheritDoc}
     */
    public function setXXAWGSTORENAME(string $XXAWG_STORE_NAME): \App\Entity\TEPSITE
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setXXAWGSTORENAME', [$XXAWG_STORE_NAME]);

        return parent::setXXAWGSTORENAME($XXAWG_STORE_NAME);
    }

    /**
     * {@inheritDoc}
     */
    public function getXXAWGSTORECITY(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getXXAWGSTORECITY', []);

        return parent::getXXAWGSTORECITY();
    }

    /**
     * {@inheritDoc}
     */
    public function setXXAWGSTORECITY(?string $XXAWG_STORE_CITY): \App\Entity\TEPSITE
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setXXAWGSTORECITY', [$XXAWG_STORE_CITY]);

        return parent::setXXAWGSTORECITY($XXAWG_STORE_CITY);
    }

    /**
     * {@inheritDoc}
     */
    public function getXXAWGSTOREADD(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getXXAWGSTOREADD', []);

        return parent::getXXAWGSTOREADD();
    }

    /**
     * {@inheritDoc}
     */
    public function setXXAWGSTOREADD(?string $XXAWG_STORE_ADD): \App\Entity\TEPSITE
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setXXAWGSTOREADD', [$XXAWG_STORE_ADD]);

        return parent::setXXAWGSTOREADD($XXAWG_STORE_ADD);
    }

    /**
     * {@inheritDoc}
     */
    public function getXXAWGSTOREPHONE(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getXXAWGSTOREPHONE', []);

        return parent::getXXAWGSTOREPHONE();
    }

    /**
     * {@inheritDoc}
     */
    public function setXXAWGSTOREPHONE(?string $XXAWG_STORE_PHONE): \App\Entity\TEPSITE
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setXXAWGSTOREPHONE', [$XXAWG_STORE_PHONE]);

        return parent::setXXAWGSTOREPHONE($XXAWG_STORE_PHONE);
    }

    /**
     * {@inheritDoc}
     */
    public function getXXAWGSTOREZIP(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getXXAWGSTOREZIP', []);

        return parent::getXXAWGSTOREZIP();
    }

    /**
     * {@inheritDoc}
     */
    public function setXXAWGSTOREZIP(string $XXAWG_STORE_ZIP): \App\Entity\TEPSITE
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setXXAWGSTOREZIP', [$XXAWG_STORE_ZIP]);

        return parent::setXXAWGSTOREZIP($XXAWG_STORE_ZIP);
    }

    /**
     * {@inheritDoc}
     */
    public function getTEPPARENTSTOREID(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTEPPARENTSTOREID', []);

        return parent::getTEPPARENTSTOREID();
    }

    /**
     * {@inheritDoc}
     */
    public function setTEPPARENTSTOREID(?int $T_EP_PARENT_STORE_ID): \App\Entity\TEPSITE
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTEPPARENTSTOREID', [$T_EP_PARENT_STORE_ID]);

        return parent::setTEPPARENTSTOREID($T_EP_PARENT_STORE_ID);
    }

}
