<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQGGUELB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQGGUELB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQGGUELB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQGGUELB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQGGUELB\App_KernelDevDebugContainer([
    'container.build_hash' => 'QGGUELB',
    'container.build_id' => 'f91704ab',
    'container.build_time' => 1607716573,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQGGUELB');
