<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYMjX3GM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYMjX3GM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYMjX3GM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYMjX3GM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYMjX3GM\App_KernelDevDebugContainer([
    'container.build_hash' => 'YMjX3GM',
    'container.build_id' => 'b103b277',
    'container.build_time' => 1607449138,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYMjX3GM');
